"""
Pitch Deck Generation API Routes.

Exposes endpoints to trigger AI slide outlines for startup fundraising pitches.
"""

import logging
from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel

from app.auth.dependencies import get_current_user
from app.services.pitch_deck_service import PitchDeckService
from app.config.mongodb_config import get_database

router = APIRouter(prefix="/pitch-decks", tags=["Pitch Decks"])
logger = logging.getLogger(__name__)


class GenerateDeckRequest(BaseModel):
    campaign_id: str = ""
    startup_name: str
    problem: str
    solution: str
    market: str
    traction: str
    competitors: str
    funding_ask: str


@router.post("/generate", summary="Generate a 10-slide startup pitch deck layout")
async def generate_pitch_deck(
    request: GenerateDeckRequest,
    current_user: dict = Depends(get_current_user)
):
    """
    Synthesize startup data into slide content for PptxGenJS compilation on the frontend.
    """
    try:
        deck = await PitchDeckService.generate_deck(
            user_id=current_user["id"],
            campaign_id=request.campaign_id,
            startup_name=request.startup_name,
            problem=request.problem,
            solution=request.solution,
            market=request.market,
            traction=request.traction,
            competitors=request.competitors,
            funding_ask=request.funding_ask
        )
        return {"status": "success", "pitch_deck": deck}
    except Exception as exc:
        logger.exception("Failed to generate pitch deck layout: %s", exc)
        raise HTTPException(status_code=500, detail=str(exc))


@router.get("/my-decks", summary="List generated pitch decks for user")
async def list_pitch_decks(
    current_user: dict = Depends(get_current_user)
):
    """Retrieve all pitch decks generated by the current user."""
    db = await get_database()
    decks = await db.pitch_decks.find({"user_id": current_user["id"]}, {"_id": 0}).to_list(length=50)
    return {"status": "success", "pitch_decks": decks}