"""
PitchDeck document model for MongoDB.

Stores metadata and slide contents generated by the AI Pitch Deck Generator
to compile presentations via PptxGenJS on the client side.
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any, List, Dict
from uuid import uuid4

from pydantic import BaseModel, Field


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


class PitchDeck(BaseModel):
    """MongoDB pitch deck document."""

    id: str = Field(default_factory=lambda: str(uuid4()))
    user_id: str
    campaign_id: str = ""
    startup_name: str
    problem: str = ""
    solution: str = ""
    market_size: str = ""
    traction: str = ""
    competitors: str = ""
    funding_ask: str = ""
    
    slides: List[Dict[str, Any]] = Field(default_factory=list)
    
    created_at: datetime = Field(default_factory=_utcnow)
    updated_at: datetime = Field(default_factory=_utcnow)

    def to_dict(self) -> Dict[str, Any]:
        data = self.model_dump()
        data["_id"] = data.pop("id")
        return data

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "PitchDeck":
        doc = dict(data)
        if "_id" in doc:
            doc["id"] = doc.pop("_id")
        return cls(**doc)